### ISSUE TITLE
How to test model?

### ISSUE THREAD

**Issue by pendex900x** [pranayKD/crnn_pytorch#2]

**Comment by pranayKD** [comment]
Hi, 

Did you mean how to test the model using pre-trained parameters model parameters? 

If yes, then you need to load the model parameter 

`new_crnn = torch.load('/content/drive/My Drive/saved_models_crnn/epoch_4 iter_999.pt')`

create dataloader from the image set,and pick any image or batch of images for ex - 
```
valid_loader = DataLoader(iamge_set, batch_size=1, shuffle=True)
img, labels = iter(valid_loader).next()
```
Predict on the image using the loaded network

```
pred = new_crnn(img.to(device))  
print(decodeLable(pred))
```
<img width="814" alt="Screen Shot 2020-06-18 at 10 22 56 PM" src="https://user-images.githubusercontent.com/65856004/85049631-8c0a4600-b1b2-11ea-8236-431a52d9a4fc.png">

**Comment by pendex900x** [comment]
Thanks for answering, when I enter this line:
`new_crnn = torch.load('/content/crnn_pytorch/epoch_5_iter_1000.pt')`

I get this error:

![image](https://user-images.githubusercontent.com/36184284/85178304-223e7a80-b24c-11ea-9786-674bded28114.png)

Do you know why? I'm trying to use the saved model that you uploaded
